name: CI
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: mysite.settings.dev
      DJANGO_SECRET_KEY: test-secret
      DJANGO_DEBUG: "True"
      DB_ENGINE: django.db.backends.sqlite3
      DB_NAME: ${{ github.workspace }}/data/test.sqlite3

    steps:
      - uses: actions/checkout@v4

      - name: Ensure data dir exists
        run: mkdir -p data

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          # если используешь pytest:
          # pip install pytest pytest-django

      - name: Django checks & DB migrate
        run: |
          python manage.py check
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput

      # - name: Run tests
      #   run: pytest -q
